services:
  - type: web
    name: pinlink
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: AUTH_PIN
        value: 198823
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: BASE_URL
        sync: false
      - key: CUSTOM_DOMAIN
        sync: false
    autoDeploy: true
    healthCheckPath: /
